# Users schema
 
# --- !Ups

CREATE TABLE USUARIO
(
     ID INT4 PRIMARY KEY,
     NOMBRES VARCHAR(50) NOT NULL,
     APELLIDOS VARCHAR(50) NOT NULL,
     USERNAME VARCHAR(50) NOT NULL,
     PASS VARCHAR(50) NOT NULL,
     FECHA_NACIMIENTO TIMESTAMP NOT NULL,
     EMAIL VARCHAR(50) NOT NULL,
     FOTO VARCHAR(50),
     TWITTER VARCHAR(50),
     FACEBOOK VARCHAR(50),
     GMAIL VARCHAR(50),
     FECHA_REGISTRO TIMESTAMP NOT NULL,
     FECHA_BAJA TIMESTAMP,
     ULTIMA_CONEXION TIMESTAMP NOT NULL,
     FK_LUGAR INT
     
);

CREATE TABLE AMISTAD
(
     FK_USUARIO1 INT4 NOT NULL,
     FK_USUARIO2 INT4 NOT NULL,
     
);

CREATE TABLE ALBUM
(
     ID INT4 PRIMARY KEY,
     NOMBRE VARCHAR(50) NOT NULL,
     PRIVACIDAD INT2 NOT NULL,
     CARATULA VARCHAR(50) NOT NULL,
     FECHA_CREACION TIMESTAMP NOT NULL,
     DESCRIPCION VARCHAR(100),
     FK_USUARIO INT4 NOT NULL
     
);

CREATE TABLE CONTENIDO_MULTIMEDIA
(
     ID INT4 PRIMARY KEY,
     TITULO VARCHAR(100) NOT NULL,
     RUTA VARCHAR(100) NOT NULL,
     FECHA_SUBIDA TIMESTAMP NOT NULL,
     RED_SOCIAL CHAR NOT NULL,
     FK_ALBUM INT4 NOT NULL
     
);

CREATE TABLE COMENTARIO
(
     ID INT4 PRIMARY KEY,
     CONTENIDO VARCHAR(500) NOT NULL,
     FECHA TIMESTAMP NOT NULL,
     FK_CONTENIDO INT4,
     FK_ALBUM INT4,
     FK_COMENTARIO INT4,
     FK_USUARIO INT4 NOT NULL
     
);

/*AGREGAR PRIMARY KEY*/
CREATE TABLE LIKE_COMENTARIO
(
     FK_USUARIO INT4 NOT NULL,
     FK_COMENTARIO INT4 NOT NULL,
     FECHA_CREACION TIMESTAMP NOT NULL
   
    
);

CREATE TABLE LIKE_CONTENIDO
(
     FK_USUARIO INT4 NOT NULL,
     FK_CONTENIDO INT4 NOT NULL,
     FECHA_CREACION TIMESTAMP NOT NULL
     
);

CREATE TABLE LIKE_ALBUM
(
     FK_USUARIO INT4 NOT NULL,
     FK_ALBUM INT4 NOT NULL,
     FECHA_CREACION TIMESTAMP NOT NULL
     
);

CREATE TABLE NOTIFICACION
(
   ID INT4 PRIMARY KEY,
   CONTENIDO VARCHAR(200) NOT NULL,
   RUTA VARCHAR(100),
   FECHA_CREACION TIMESTAMP NOT NULL

);

CREATE TABLE NOTIFICACION_USUARIO
(
      FK_USUARIO INT4 NOT NULL,
      FK_NOTIFICACION INT4 NOT NULL
);

CREATE TABLE LUGAR
(
    ID INT4 PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    TIPO VARCHAR(15) NOT NULL,
    FK_LUGAR INT4
);

ALTER TABLE USUARIO ADD CONSTRAINT FK_LUGAR_USER FOREIGN KEY(FK_LUGAR) REFERENCES LUGAR(ID) ON DELETE SET NULL;
ALTER TABLE AMISTAD ADD CONSTRAINT FK_USER_USER1 FOREIGN KEY(FK_USUARIO1) REFERENCES USUARIO(ID) ON DELETE CASCADE;
ALTER TABLE AMISTAD ADD CONSTRAINT FK_USER_USER2 FOREIGN KEY(FK_USUARIO2) REFERENCES USUARIO(ID) ON DELETE CASCADE;
ALTER TABLE ALBUM ADD CONSTRAINT FK_USER_ALBUM FOREIGN KEY(FK_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE;
ALTER TABLE CONTENIDO_MULTIMEDIA ADD CONSTRAINT FK_ALBUM_CONTENT FOREIGN KEY(FK_ALBUM) REFERENCES ALBUM(ID) ON DELETE CASCADE;
ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENT_ALBUM FOREIGN KEY(FK_ALBUM) REFERENCES ALBUM(ID) ON DELETE CASCADE;
ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENT_COMENT FOREIGN KEY(FK_COMENTARIO) REFERENCES COMENTARIO(ID) ON DELETE CASCADE;
ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENT_CONTENT FOREIGN KEY(FK_CONTENIDO) REFERENCES CONTENIDO_MULTIMEDIA(ID) ON DELETE CASCADE;
ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENT_USER FOREIGN KEY(FK_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE;
ALTER TABLE LIKE_COMENTARIO ADD CONSTRAINT FK_COMENT_LIKE FOREIGN KEY(FK_COMENTARIO) REFERENCES COMENTARIO(ID) ON DELETE CASCADE;
ALTER TABLE LIKE_COMENTARIO ADD CONSTRAINT FK_USER_LIKE FOREIGN KEY(FK_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE;
ALTER TABLE LIKE_CONTENIDO ADD CONSTRAINT FK_CONTENT_LIKE FOREIGN KEY(FK_CONTENIDO) REFERENCES CONTENIDO_MULTIMEDIA(ID) ON DELETE CASCADE;
ALTER TABLE LIKE_CONTENIDO ADD CONSTRAINT FK_USER_LIKE_CON FOREIGN KEY(FK_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE;
ALTER TABLE LIKE_ALBUM ADD CONSTRAINT FK_ALBUM_LIKE FOREIGN KEY(FK_ALBUM) REFERENCES ALBUM(ID) ON DELETE CASCADE;
ALTER TABLE LIKE_ALBUM ADD CONSTRAINT FK_USER_LIKE_ALB FOREIGN KEY(FK_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE;
ALTER TABLE NOTIFICACION_USUARIO ADD CONSTRAINT FK_USER_NOTIFI FOREIGN KEY(FK_NOTIFICACION) REFERENCES NOTIFICACION(ID) ON DELETE CASCADE;
ALTER TABLE NOTIFICACION_USUARIO ADD CONSTRAINT FK_USER_USER FOREIGN KEY(FK_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE;
ALTER TABLE LUGAR ADD CONSTRAINT FK_LUGAR_LUGAR FOREIGN KEY(FK_LUGAR) REFERENCES LUGAR(ID) ON DELETE CASCADE;

ALTER TABLE AMISTAD ADD CONSTRAINT PK_AMISTAD PRIMARY KEY(FK_USUARIO1,FK_USUARIO2);
ALTER TABLE LIKE_COMENTARIO ADD CONSTRAINT PK_LIKE_COMENT PRIMARY KEY(FK_USUARIO,FK_COMENTARIO);
ALTER TABLE LIKE_ALBUM ADD CONSTRAINT PK_LIKE_ALBUM PRIMARY KEY(FK_USUARIO,FK_ALBUM);
ALTER TABLE LIKE_CONTENIDO ADD CONSTRAINT PK_LIKE_CONTENT PRIMARY KEY(FK_USUARIO,FK_CONTENIDO);
ALTER TABLE NOTIFICACION_USUARIO ADD CONSTRAINT PK_NOTIFI_USER PRIMARY KEY(FK_USUARIO,FK_NOTIFICACION);



INSERT INTO USUARIO VALUES(1,'Juan Pablo','Amorin Martinez','THE BIG BOSS','17125987','1986-02-10','juan_amorin$hotmail.com','assets/images/user_images/juan.jpg',null,null,null,'1986-02-10',null,'1986-02-10',null);
INSERT INTO USUARIO VALUES(2,'Rene','Barbosa','rbarbosa','12345678','1986-02-10','rbarbosa$hotmail.com','assets/images/user_images/rene.jpg',null,null,null,'1986-02-10',null,'1986-02-10',null);
INSERT INTO USUARIO VALUES(3,'Rafael','Gutierrez','rguti','12345678','1986-02-10','rguti$hotmail.com','assets/images/user_images/rafael.jpg',null,null,null,'1986-02-10',null,'1986-02-10',null);


INSERT INTO ALBUM VALUES(1,'mis fotos de prueba',1,'assets/images/folder.jpg','1986-02-10','Este es mi album',2);
INSERT INTO ALBUM VALUES(2,'mis fotos de prueba2',1,'assets/images/folder.jpg','1986-02-10','Este es mi album2',2);
INSERT INTO ALBUM VALUES(3,'mis fotos de prueba',1,'assets/images/folder.jpg','1986-02-10','Este es mi album3',2);
INSERT INTO ALBUM VALUES(4,'mis fotos de prueba2',1,'assets/images/folder.jpg','1986-02-10','Este es mi album4',2);
INSERT INTO ALBUM VALUES(5,'mis fotos de prueba2',1,'assets/images/folder.jpg','1986-02-10','Este es mi album5',2);

INSERT INTO AMISTAD VALUES(1,2);
INSERT INTO AMISTAD VALUES(1,3);
INSERT INTO AMISTAD VALUES(3,2);

# --- !Downs
 
DROP TABLE USUARIO;
DROP TABLE USUARIO;
DROP TABLE AMISTAD;
DROP TABLE ALBUM;
DROP TABLE CONTENIDO_MULTIMEDIA;
DROP TABLE COMENTARIO;
DROP TABLE LIKE_COMENTARIO;
DROP TABLE LIKE_ALBUM;
DROP TABLE LIKE_CONTENIDO;
DROP TABLE NOTIFICACION;
DROP TABLE NOTIFICACION_USUARIO;
DROP TABLE LUGAR;