# Users schema
 
# --- !Ups

CREATE SEQUENCE seq_album START 1;
CREATE SEQUENCE seq_usuario START 1;
CREATE SEQUENCE seq_lugar START 1;
CREATE SEQUENCE seq_notificacion START 1;
CREATE SEQUENCE seq_contenido START 1;
CREATE SEQUENCE seq_comentario START 1;
CREATE SEQUENCE seq_like START 1;


CREATE TABLE USUARIO
(
     ID INT4 PRIMARY KEY,
     PRIMER_NOMBRE VARCHAR(50) NOT NULL,
     SEGUNDO_NOMBRE VARCHAR(50),
     PRIMER_APELLIDO VARCHAR(50) NOT NULL,
     SEGUNDO_APELLIDO VARCHAR(50),
     USERNAME VARCHAR(50) NOT NULL,
     FECHA_NACIMIENTO TIMESTAMP NOT NULL,
     EMAIL VARCHAR(50) NOT NULL,
     FOTO VARCHAR(50),
     TWITTER VARCHAR(50),
     FACEBOOK VARCHAR(50),
     GMAIL VARCHAR(50),
     FECHA_REGISTRO TIMESTAMP NOT NULL,
     FECHA_BAJA TIMESTAMP,
     ULTIMA_CONEXION TIMESTAMP NOT NULL,
     PRIVACIDAD INT NOT NULL,
     FK_LUGAR INT,
     LATITUD VARCHAR(25) NOT NULL,
     LONGITUD VARCHAR(25) NOT NULL,
     FACEBOOK_ID VARCHAR(20) NOT NULL
     
     
);

CREATE TABLE AMISTAD
(
     FK_USUARIO1 INT4 NOT NULL,
     FK_USUARIO2 INT4 NOT NULL,
     STATUS INT NOT NULL
     
);

CREATE TABLE ALBUM
(
     ID INT4 PRIMARY KEY,
     NOMBRE VARCHAR(50) NOT NULL,
     PRIVACIDAD INT NOT NULL,
     CARATULA VARCHAR(50) NOT NULL,
     FECHA_CREACION TIMESTAMP NOT NULL,
     DESCRIPCION VARCHAR(100),
     FK_USUARIO INT4 NOT NULL
     
);

CREATE TABLE CONTENIDO_MULTIMEDIA
(
     ID INT4 PRIMARY KEY,
     RUTA VARCHAR(200) NOT NULL,
     FECHA_SUBIDA TIMESTAMP NOT NULL,
     RED_SOCIAL VARCHAR(15) NOT NULL,
     RUTA_TUMBNAIL VARCHAR(200) NOT NULL,
     FK_ALBUM INT4 NOT NULL
     
);

CREATE TABLE NOTIFICACION
(
   ID INT4 PRIMARY KEY,
   CONTENIDO VARCHAR(200) NOT NULL,
   FECHA_CREACION TIMESTAMP NOT NULL,
   FK_AMIGO INT4,
   ID_USUARIO_GENERADOR INT4 NOT NULL,
   FK_TIPO INT4 NOT NULL

);

CREATE TABLE TIPO_NOTIFICACION
(
     ID INT4 PRIMARY KEY,
     NOMBRE VARCHAR(20) NOT NULL
     
);

CREATE TABLE NOTIFICACION_USUARIO
(
      FK_USUARIO INT4 NOT NULL,
      FK_NOTIFICACION INT4 NOT NULL
);

CREATE TABLE LUGAR
(
    ID INT4 PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    TIPO VARCHAR(15) NOT NULL,
    FK_LUGAR INT4
    
);

CREATE TABLE COMENTARIO
(
     ID INT4 PRIMARY KEY,
     CONTENIDO VARCHAR(500) NOT NULL,
     FECHA TIMESTAMP NOT NULL,
     FK_CONTENIDO INT4,
     FK_ALBUM INT4,
     FK_COMENTARIO INT4,
     FK_USUARIO INT4 NOT NULL
     
);

CREATE TABLE TLIKE
(
     ID INT4 PRIMARY KEY,
     TIPO VARCHAR(1) NOT NULL,
     FECHA TIMESTAMP NOT NULL,
     FK_CONTENIDO INT4,
     FK_ALBUM INT4,
     FK_COMENTARIO INT4,
     FK_USUARIO INT4 NOT NULL
     
);


ALTER TABLE USUARIO ADD CONSTRAINT FK_LUGAR_USER FOREIGN KEY(FK_LUGAR) REFERENCES LUGAR(ID) ON DELETE SET NULL;
ALTER TABLE AMISTAD ADD CONSTRAINT FK_USER_USER1 FOREIGN KEY(FK_USUARIO1) REFERENCES USUARIO(ID) ON DELETE CASCADE;
ALTER TABLE AMISTAD ADD CONSTRAINT FK_USER_USER2 FOREIGN KEY(FK_USUARIO2) REFERENCES USUARIO(ID) ON DELETE CASCADE;
ALTER TABLE ALBUM ADD CONSTRAINT FK_USER_ALBUM FOREIGN KEY(FK_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE;
ALTER TABLE CONTENIDO_MULTIMEDIA ADD CONSTRAINT FK_ALBUM_CONTENT FOREIGN KEY(FK_ALBUM) REFERENCES ALBUM(ID) ON DELETE CASCADE;

ALTER TABLE NOTIFICACION_USUARIO ADD CONSTRAINT FK_USER_NOTIFI FOREIGN KEY(FK_NOTIFICACION) REFERENCES NOTIFICACION(ID) ON DELETE CASCADE;
ALTER TABLE NOTIFICACION_USUARIO ADD CONSTRAINT FK_USER_USER FOREIGN KEY(FK_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE;
ALTER TABLE LUGAR ADD CONSTRAINT FK_LUGAR_LUGAR FOREIGN KEY(FK_LUGAR) REFERENCES LUGAR(ID) ON DELETE CASCADE;
ALTER TABLE NOTIFICACION ADD CONSTRAINT FK_NOTIFI_USUARIO FOREIGN KEY(FK_AMIGO) REFERENCES USUARIO(ID) ON DELETE SET NULL;
ALTER TABLE NOTIFICACION ADD CONSTRAINT FK_NOTIFI_TIPO FOREIGN KEY(FK_TIPO) REFERENCES TIPO_NOTIFICACION(ID) ON DELETE CASCADE;

ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENT_ALBUM FOREIGN KEY(FK_ALBUM) REFERENCES ALBUM(ID) ON DELETE CASCADE;
ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENT_COMENT FOREIGN KEY(FK_COMENTARIO) REFERENCES COMENTARIO(ID) ON DELETE CASCADE;
ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENT_CONTENT FOREIGN KEY(FK_CONTENIDO) REFERENCES CONTENIDO_MULTIMEDIA(ID) ON DELETE CASCADE;
ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENT_USER FOREIGN KEY(FK_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE;

ALTER TABLE AMISTAD ADD CONSTRAINT PK_AMISTAD PRIMARY KEY(FK_USUARIO1,FK_USUARIO2);

ALTER TABLE NOTIFICACION_USUARIO ADD CONSTRAINT PK_NOTIFI_USER PRIMARY KEY(FK_USUARIO,FK_NOTIFICACION);

INSERT INTO TIPO_NOTIFICACION VALUES(1,'SOLICITUD');
INSERT INTO TIPO_NOTIFICACION VALUES(2,'LIKE');
INSERT INTO TIPO_NOTIFICACION VALUES(3,'COMENTARIO');
INSERT INTO TIPO_NOTIFICACION VALUES(4,'AMISTAD');
INSERT INTO TIPO_NOTIFICACION VALUES(5,'ALBUM');
INSERT INTO TIPO_NOTIFICACION VALUES(6,'MULTIMEDIA');

# --- !Downs

DROP SEQUENCE seq_album;
DROP SEQUENCE seq_usuario;
DROP SEQUENCE seq_lugar;
DROP SEQUENCE seq_notificacion;
DROP SEQUENCE seq_contenido;
DROP SEQUENCE seq_comentario;
 
DROP TABLE USUARIO;
DROP TABLE USUARIO;
DROP TABLE AMISTAD;
DROP TABLE ALBUM;
DROP TABLE CONTENIDO_MULTIMEDIA;
DROP TABLE NOTIFICACION;
DROP TABLE NOTIFICACION_USUARIO;
DROP TABLE LUGAR;
DROP TABLE COMENTARIO;
DROP TABLE LIKE;